FROM alpine:3.8
MAINTAINER exelban

ENV \
    TERM=xterm-256color        \
    DINIT_VERSION=1.2.1        \
    USER=app                 \
    MYUID=1001                 \
    DOCKER_GID=999

RUN echo "Hello world"

